# App
spring.application.name=smart-campus

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/smartcampus
spring.datasource.username=postgres
spring.datasource.password=Rekha4387#
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=smartcampus-super-secret-key-2024-must-be-very-long-for-security
jwt.expiration=86400000

# Server
server.port=8080

# Logging
logging.level.com.smartcampus=DEBUG
logging.level.org.springframework.security=DEBUG

# ─────────────────────────────────────
# Gemini AI
# ─────────────────────────────────────
gemini.api.key=AIzaSyDfNH4SdNWc8oOITJ3EJCKQSG2Q8mYaZW0
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.model=gemini-1.5-flash

# ─────────────────────────────────────
# College Details
# ─────────────────────────────────────
college.name=MIT World Peace University
college.short.name=MIT-WPU
college.location=Pune